apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jenniferosei/eks-gitops-platform.git
    targetRevision: HEAD
    path: apps/vault
    helm:
      valueFiles:
        - values.yaml
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
