server:
  dev:
    enabled: true

  extraEnvironmentVars:
    VAULT_DEV_ROOT_TOKEN_ID: root

  dataStorage:
    enabled: false

injector:
  enabled: true

ui:
  enabled: true

global:
  tlsDisable: true
